### ISSUE TITLE
Troubles on FreeBSD

### ISSUE THREAD

**Issue by ghost** [mkarpoff/vim8-pack#1]
Hi,
I'm trying to run vim8-pack on FreeBSD and I'm having some trouble.

First, `/bin/bash` is not present on FreeBSD (and I think in all *BSD, but I'm not sure). For instance, I have `bash` in `/usr/local/bin/bash`. I'm going to make a PR to achieve this issue (just use `/usr/bin/env bash` instead, easy).

Last, here on FreeBSD `getopt` does not have `--longoptions` (a simple `man getopt | grep -i long` doesn't find anything). I think that should be a GNU extension, although I've not checked yet.

**Comment by mkarpoff** [comment]
Re-read I'll have to look into the replacement for longopts.

**Comment by ghost** [comment]
if it can helps, based on [this](https://unix.stackexchange.com/questions/315858/how-can-options-be-parsed-in-a-bash-script-leaving-unrecognized-options-after-t) I've come up with:

```bash
#!/usr/bin/env bash

# test-opt.bash

silent=false
repo_dir=$HOME/.vim/pack/git-plugins

opt=("$@")
while getopts ":s:d:-:" chr "${opt[@]}"; do
    case "$chr" in
        -)  case "$OPTARG" in
                git-dir)
                    repo_dir="${opt[$OPTIND-1]}"
                    ((OPTIND++))
                    ;;

                silent)
                    silent=true
                    ;;

                *) ((OPTIND--)); break;;
            esac;;

        # Redirect short arguments to long arguments
        s)    ((OPTIND-=2)); opt[OPTIND-1]="--silent";;
        d)    ((OPTIND-=2)); opt[OPTIND-1]="--git-dir";;

        *)    ((OPTIND--)); break;;
    esac
done

# remaining options
opt=( "${opt[@]:$OPTIND-1}" )
echo "REMAINING Options: ${opt[@]}"


echo '$silent   = ' $silent
echo '$repo_dir = ' $repo_dir
```

here's some tests: (only 2 for brevity)
```bash
➤ ./test-opt.bash --silent -d ~/build
REMAINING Options: 
$silent   =  true
$repo_dir =  /usr/home/omar/build
```

```bash
➤ ./test-opt.bash -s --git-dir ~/build -a
REMAINING Options: -a
$silent   =  true
$repo_dir =  /usr/home/omar/build
```

and that's working fine on FreeBSD. I haven't tested (yet) on linux, although I don't think there will be problems

**Comment by mkarpoff** [comment]
I was thinking about this and switching to python instead of using shell script might be the way to go. It is easier to handle a wider range of systems and making a windows complient version would be easy too.
